[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "orbit3d-hub"
version = "0.2.1"
description = "Orbit3D input provider and application SDK"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE"]

[tool.setuptools.packages.find]
where = ["src"]
